"""add applied_at to pending_changes

Revision ID: 045f796c6091
Revises: a72b2bd4c5df
Create Date: 2026-05-03 12:05:09.321090

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "045f796c6091"
down_revision: str | Sequence[str] | None = "a72b2bd4c5df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pending_changes", sa.Column("applied_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pending_changes", "applied_at")
    # ### end Alembic commands ###
