"""Add inheritance column to variant_classifications

Revision ID: 221538ef3882
Revises: 7164749c4b0c
Create Date: 2026-05-06 23:48:40.079553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221538ef3882'
down_revision: Union[str, Sequence[str], None] = '7164749c4b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_classifications', sa.Column('inheritance', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_classifications', 'inheritance')
    # ### end Alembic commands ###
