"""add gnomad_af and aou_af columns

Revision ID: 22820da06f25
Revises: 361dcc08bce4
Create Date: 2026-05-19 15:32:03.418244

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "22820da06f25"
down_revision: str | Sequence[str] | None = "361dcc08bce4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
