"""remove_cadd_score_column

Revision ID: 361dcc08bce4
Revises: 221538ef3882
Create Date: 2026-05-19 14:10:36.809680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361dcc08bce4'
down_revision: Union[str, Sequence[str], None] = '221538ef3882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'cadd_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('cadd_score', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
