"""Remove disease from literature table

Revision ID: 526ecfbfda57
Revises: 8d3bf8581db3
Create Date: 2026-05-06 22:55:45.983806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526ecfbfda57'
down_revision: Union[str, Sequence[str], None] = '8d3bf8581db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('literature', 'disease')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literature', sa.Column('disease', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
