"""Remove clinvar_significance from variant_classifications

Revision ID: 7164749c4b0c
Revises: 526ecfbfda57
Create Date: 2026-05-06 23:31:11.743440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7164749c4b0c'
down_revision: Union[str, Sequence[str], None] = '526ecfbfda57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_classifications', 'clinvar_significance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_classifications', sa.Column('clinvar_significance', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
