"""Add FK constraints, indexes, fix Literature.year type

Revision ID: 7a74c0a68a93
Revises: 22820da06f25
Create Date: 2026-05-20 15:40:00.192698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a74c0a68a93'
down_revision: Union[str, Sequence[str], None] = '22820da06f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'annotations', 'rna_structures', ['structure_id'], ['id'])
    op.create_foreign_key(None, 'base_pairs', 'rna_structures', ['structure_id'], ['id'])
    op.create_index(op.f('ix_bed_tracks_geneId'), 'bed_tracks', ['geneId'], unique=False)
    op.create_foreign_key(None, 'bed_tracks', 'genes', ['geneId'], ['id'])
    op.alter_column('literature', 'year',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'nucleotides', 'rna_structures', ['structure_id'], ['id'])
    op.create_index(op.f('ix_pending_changes_requested_by'), 'pending_changes', ['requested_by'], unique=False)
    op.create_index(op.f('ix_rna_structures_geneId'), 'rna_structures', ['geneId'], unique=False)
    op.create_foreign_key(None, 'rna_structures', 'genes', ['geneId'], ['id'])
    op.create_foreign_key(None, 'structural_features', 'rna_structures', ['structure_id'], ['id'])
    op.create_foreign_key(None, 'variant_classifications', 'variants', ['variant_id'], ['id'])
    op.create_foreign_key(None, 'variant_classifications', 'literature', ['literature_id'], ['id'])
    op.create_foreign_key(None, 'variant_links', 'variants', ['variant_id_2'], ['id'])
    op.create_foreign_key(None, 'variant_links', 'variants', ['variant_id_1'], ['id'])
    op.create_index(op.f('ix_variants_geneId'), 'variants', ['geneId'], unique=False)
    op.create_foreign_key(None, 'variants', 'genes', ['geneId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variants', type_='foreignkey')
    op.drop_index(op.f('ix_variants_geneId'), table_name='variants')
    op.drop_constraint(None, 'variant_links', type_='foreignkey')
    op.drop_constraint(None, 'variant_links', type_='foreignkey')
    op.drop_constraint(None, 'variant_classifications', type_='foreignkey')
    op.drop_constraint(None, 'variant_classifications', type_='foreignkey')
    op.drop_constraint(None, 'structural_features', type_='foreignkey')
    op.drop_constraint(None, 'rna_structures', type_='foreignkey')
    op.drop_index(op.f('ix_rna_structures_geneId'), table_name='rna_structures')
    op.drop_index(op.f('ix_pending_changes_requested_by'), table_name='pending_changes')
    op.drop_constraint(None, 'nucleotides', type_='foreignkey')
    op.alter_column('literature', 'year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'bed_tracks', type_='foreignkey')
    op.drop_index(op.f('ix_bed_tracks_geneId'), table_name='bed_tracks')
    op.drop_constraint(None, 'base_pairs', type_='foreignkey')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    # ### end Alembic commands ###
