"""add variant_classifications table and literature pmid url disease columns

Revision ID: 8d3bf8581db3
Revises: a7de7261403c
Create Date: 2026-05-06 18:51:37.396833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d3bf8581db3'
down_revision: Union[str, Sequence[str], None] = 'a7de7261403c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_classifications',
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('literature_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clinical_significance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zygosity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disease', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('linked_variant_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clinvar_significance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('variant_id', 'literature_id')
    )
    op.drop_table('literature_counts')
    op.add_column('literature', sa.Column('pmid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('literature', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('literature', sa.Column('disease', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('variants', 'disease_type')
    op.drop_column('variants', 'pmid')
    op.drop_column('variants', 'ukbb_ac')
    op.drop_column('variants', 'ukbb_hom')
    op.drop_column('variants', 'clinical_significance')
    op.drop_column('variants', 'cohort')
    op.drop_column('variants', 'zygosity')
    op.drop_column('variants', 'clinvar_significance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('clinvar_significance', sa.VARCHAR(), nullable=True))
    op.add_column('variants', sa.Column('zygosity', sa.VARCHAR(), nullable=True))
    op.add_column('variants', sa.Column('cohort', sa.VARCHAR(), nullable=True))
    op.add_column('variants', sa.Column('clinical_significance', sa.VARCHAR(), nullable=True))
    op.add_column('variants', sa.Column('ukbb_hom', sa.INTEGER(), nullable=True))
    op.add_column('variants', sa.Column('ukbb_ac', sa.INTEGER(), nullable=True))
    op.add_column('variants', sa.Column('pmid', sa.VARCHAR(), nullable=True))
    op.add_column('variants', sa.Column('disease_type', sa.VARCHAR(), nullable=True))
    op.drop_column('literature', 'disease')
    op.drop_column('literature', 'url')
    op.drop_column('literature', 'pmid')
    op.create_table('literature_counts',
    sa.Column('variant_id', sa.VARCHAR(), nullable=False),
    sa.Column('literature_id', sa.VARCHAR(), nullable=False),
    sa.Column('counts', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('variant_id', 'literature_id')
    )
    op.drop_table('variant_classifications')
    # ### end Alembic commands ###
