"""initial_sqlmodel_schema

Revision ID: a72b2bd4c5df
Revises: 
Create Date: 2026-05-03 02:59:45.213722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a72b2bd4c5df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('structure_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'structure_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('user_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint("action IN ('CREATE', 'UPDATE', 'DELETE')", name='check_action'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_pairs',
    sa.Column('structure_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_pos', sa.Integer(), nullable=False),
    sa.Column('to_pos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('structure_id', 'from_pos', 'to_pos')
    )
    op.create_table('bed_tracks',
    sa.Column('geneId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('track_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chrom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_start', sa.Integer(), nullable=False),
    sa.Column('interval_end', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fullName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chromosome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('strand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('journal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature_counts',
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('literature_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('variant_id', 'literature_id')
    )
    op.create_table('nucleotides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'structure_id')
    )
    op.create_table('pending_changes',
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'delete')", name='check_action'),
    sa.CheckConstraint("entity_type IN ('gene', 'variant', 'literature', 'structure', 'bed_track')", name='check_entity_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='check_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rna_structures',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geneId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structural_features',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('structure_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nucleotide_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label_x', sa.Float(), nullable=False),
    sa.Column('label_y', sa.Float(), nullable=False),
    sa.Column('label_font_size', sa.Integer(), nullable=False),
    sa.Column('label_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'structure_id')
    )
    op.create_table('users',
    sa.Column('github_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('guest', 'pending', 'curator', 'admin')", name='check_role'),
    sa.PrimaryKeyConstraint('github_login')
    )
    op.create_table('variant_links',
    sa.Column('variant_id_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_id_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint('variant_id_1 < variant_id_2'),
    sa.PrimaryKeyConstraint('variant_id_1', 'variant_id_2')
    )
    op.create_table('variants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geneId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('nucleotidePosition', sa.Integer(), nullable=True),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hgvs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clinvar_significance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clinical_significance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disease_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pmid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('function_score', sa.Float(), nullable=True),
    sa.Column('pvalues', sa.Float(), nullable=True),
    sa.Column('qvalues', sa.Float(), nullable=True),
    sa.Column('depletion_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gnomad_ac', sa.Integer(), nullable=True),
    sa.Column('gnomad_hom', sa.Integer(), nullable=True),
    sa.Column('aou_ac', sa.Integer(), nullable=True),
    sa.Column('aou_hom', sa.Integer(), nullable=True),
    sa.Column('ukbb_ac', sa.Integer(), nullable=True),
    sa.Column('ukbb_hom', sa.Integer(), nullable=True),
    sa.Column('cadd_score', sa.Float(), nullable=True),
    sa.Column('zygosity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cohort', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variants')
    op.drop_table('variant_links')
    op.drop_table('users')
    op.drop_table('structural_features')
    op.drop_table('rna_structures')
    op.drop_table('pending_changes')
    op.drop_table('nucleotides')
    op.drop_table('literature_counts')
    op.drop_table('literature')
    op.drop_table('genes')
    op.drop_table('bed_tracks')
    op.drop_table('base_pairs')
    op.drop_table('audit_log')
    op.drop_table('annotations')
    # ### end Alembic commands ###
