"""actually add gnomad_af and aou_af columns to variants table

Revision ID: b051df0029e7
Revises: 7a74c0a68a93
Create Date: 2026-05-20 21:20:56.680022

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b051df0029e7"
down_revision: str | Sequence[str] | None = "7a74c0a68a93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("variants", sa.Column("gnomad_af", sa.Float(), nullable=True))
    op.add_column("variants", sa.Column("aou_af", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("variants", "aou_af")
    op.drop_column("variants", "gnomad_af")
    # ### end Alembic commands ###
